name = "midicaltest"
main = "worker.js"
compatibility_date = "2024-03-01"

account_id = "2069e309de540db18def59b77f186f93"

[vars]
SITE_URL = "http://localhost:8787"
PAYTABS_REGION = "GLOBAL"
PAYTABS_CURRENCY = "IQD"

[[kv_namespaces]]
binding = "SESSIONS"
id ="99020b874a87463fa4ee36cd76c54407"

[[kv_namespaces]]
binding = "PAID"
id = "ddccc2fbd74f453ca10fb3e85318b4fa"

[[d1_databases]]
binding = "DB"
database_name = "omsprep-db"
database_id = "867fd320-b61f-4b7b-96c9-e6a381d1d694"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "medical_books_index"
